### ISSUE TITLE
Why does -l2 in the palm tree of my website show bingoporno.com ?

### ISSUE THREAD

**Issue by principal-aaas** [Malwarize/webpalm#18]
I hope my peers and family members do not run -l2 against my domain, or I'll have some explaining to do...lol. 

./webpalm -u https://all-around-audit-solutions.com -l2 --live

        ├── [https://www.bingoporno.com/](200)

**Comment by MahdiAw** [comment]
this is not an issue ;)

**Comment by elhirchek** [comment]
Dear @principal-aaas ,

As mentioned by @MahdiAw , this is not an issue. Additionally, let me provide an explanation regarding the `-l` option.
The option `-l or --level` specifies the depth to which you want the crawler to navigate. For instance, if you set it to `-l1`, you will only receive the websites within your own domain or the domain specified by the `-u` option. However, if you set it to `-l2`, the crawler will extract links from the websites you are currently pointing to.

```bash
webpalm -u https://yourdomain.com -l1 --live
# output:
# └── [https://yourdomin.com/](200)
#   ├── [https://some_other_domain_you_are_pointing_to.com](200)
webpalm -u https://some_other_domain_you_are_pointing_to.com -l1 --live
# output:
# └── [https://some_other_domain_you_are_pointing_to.com/](200)
#   ├── [https://domains.com](200)
```
is equivalent to
```bash
webpalm -u https://yourdomain.com -l2 --live
#output:
# output:
# └── [https://yourdomin.com/](200)
#  ├── [https://some_other_domain_you_are_pointing_to.com](200)
#   ├── [https://domains.com](200)
```

Please let me know if you require any further clarification.
