### ISSUE TITLE
Regex errors

### ISSUE THREAD

**Issue by AAVision** [Malwarize/webpalm#25]
while running the following command as mentioned in the documentation (readme file):
`webpalm -u https://google.com -l1 --regexes comments="\<\!--.*?-->",emails="([a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+)"
`

I'm getting the following error:

`Error: invalid argument "comments=\\<\\!--.*?-->,emails=([a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+)" for "--regexes"`

**Comment by XORbit01** [comment]
Thank you for opening this issue! 
problem is solved in the latest release v2.0.17 https://github.com/Malwarize/webpalm/commit/22a53006124c7ab2a91d94de68244f16de4835ac
