### ISSUE TITLE
Long runs do not respond to Ctrl-C

### ISSUE THREAD

**Issue by ranlo** [Malwarize/webpalm#4]
On macOS Ventura 13.4 (22F66), I'm trying to run:

`webpalm  -u https://www.nammalonline.co.il/ -l2 -i nammalonline.co.il`

if I try to stop the run by pressing ^C, it does not respond

**Comment by XORbit01** [comment]
I test it 
it work fine with SIG INT 
are you sure that you are not running it on the background?
