### ISSUE TITLE
runtime: failed to create new OS thread

### ISSUE THREAD

**Issue by ranlo** [Malwarize/webpalm#5]
trying to run

`webpalm  -u https://www.nammalonline.co.il/ -l3 -i nammalonline.co.il`

After a few seconds I'm getting an error message saying 

`runtime: failed to create new OS thread`

This could be due to the number of pages it is trying to simultaneously crawl, or due to new threads getting created faster than the existing ones are completing their work. The number of threads on `top` jumped from 12K to 18K in a few seconds, and then webpalm (which was eating up 1800% CPU) crashed.

I think some control on the number of simultaneous threads is required.

**Comment by XORbit01** [comment]
we should add some maximum threads number option
