### ISSUE TITLE
webpalm on URLs which are open to directory listing returns nothing

### ISSUE THREAD

**Issue by ranlo** [Malwarize/webpalm#6]
running `webpalm  -u https://www.nammalonline.co.il/wp-content/uploads/ -l3 -i nammalonline.co.il`
returns:

```
┌[https://www.nammalonline.co.il/wp-content/uploads/]
│Level: 3
│Live Mode: false
│Export to: nothing
│Regexes:
│  nothing
│Crawl Only :
│  nammalonline.co.il
│Excluded Status: nothing
└
└── [https://www.nammalonline.co.il/wp-content/uploads/](0)
```

even though the uploads directory is open for browsing and contains multiple URLs to crawl.

**Comment by XORbit01** [comment]
the return value is 0 so the page is not loaded for several reasons 
maybe it require some headers or block your IP address
please give another similar  general no governable domain name to try on it. 
I can't  open this site for personal reasons

**Comment by ranlo** [comment]
`./webpalm -u https://www.rothcheese.com/wp-content/uploads/ -l 2`

returns

```
      ////    //////
   ////  /// //    //
  //  ///////////   /
  /  //    ##   /// /  WEBPALM
 // //     ##     / /
  / /     ###    //
    /     ###    /
         ####
         ####
        ####
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$ webpalm v1.1.1
$ author github.com/Malwarize
$ discord discord.gg/g9y7D3xCab
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
┌[https://www.rothcheese.com/wp-content/uploads/]
│Level: 2
│Live Mode: false
│Export to: nothing
│Regexes:
│  nothing
│Crawl Only :
│  all
│Excluded Status: nothing
└
└── [https://www.rothcheese.com/wp-content/uploads/](200)
```

and stops, although outgoing links from the page are present

**Comment by XORbit01** [comment]
Unfortunately, the tool only traverse  the paths in which it find the regex of a full link (it traverses `google.com/hello` but not `/hello`)
 but since there are no links in the index files pages, you will not be able to access them.
so we can add some optional features that we can search for `<a href="http://url.com">` tag  and catch the url from it

**Comment by XORbit01** [comment]
I do some changes adding href scraping engine 
it  explore the relative tasks then convert it to absolute path
you can test the new feature
